# rancher server backup image
FROM alpine
MAINTAINER software@tradertools.com

# smb port
EXPOSE 445

# install the necessary client
RUN apk add --update bash samba-server && rm -rf /var/cache/apk/* && touch /etc/samba/smb.conf

# enter smb.conf
COPY smb.conf /etc/samba/
COPY smbusers /etc/samba/
COPY *.tdb /var/lib/samba/private/
# create a user with no home directory but the right password
RUN adduser user -D -H
RUN echo user:pass | chpasswd

# run samba in the foreground
ENTRYPOINT ["/usr/sbin/smbd"]
CMD ["-F"]

