# circleci to build and test; deploy when on master
---
version: 2.1
jobs:
  ci:
    docker:
      - image: alpine:3.10
    steps:
      - run:
          name: Add dependencies
          command: apk --update add make docker bash ca-certificates git
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      # no need to install docker, as it is included in the above circleci/ruby image
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: build
          command: make build
      - run:
          name: test
          command: make test DEBUG=debug
  deploy:
    docker:
      - image: alpine:3.10
    steps:
      - run:
          name: Add dependencies
          command: apk --update add make docker bash ca-certificates git
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - attach_workspace:
          at: .
      - run:
          name: push
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            make push

workflows:
  version: 2
  test-deploy:
    jobs:
      - ci
      - deploy:
          requires:
          - ci
          filters:
            branches:
              only: master
